export type DivineName = {
  number: number;
  arabic: string;
  transliteration: string;
  english: string;
  urdu: string;
};

export const divineNames: DivineName[] = [
  { number: 1, arabic: 'الرَّحْمَٰن', transliteration: 'Ar-Rahman', english: 'The Most Compassionate', urdu: 'نہایت مہربان' },
  { number: 2, arabic: 'الرَّحِيم', transliteration: 'Ar-Raheem', english: 'The Most Merciful', urdu: 'بے حد رحم کرنے والا' },
  { number: 3, arabic: 'الْمَلِك', transliteration: 'Al-Malik', english: 'The King, Sovereign', urdu: 'بادشاہ' },
  { number: 4, arabic: 'الْقُدُّوس', transliteration: 'Al-Quddus', english: 'The Most Holy', urdu: 'نہایت پاک' },
  { number: 5, arabic: 'السَّلَام', transliteration: 'As-Salam', english: 'The Source of Peace', urdu: 'سلامتی دینے والا' },
  { number: 6, arabic: 'الْمُؤْمِن', transliteration: "Al-Mu'min", english: 'The Giver of Faith', urdu: 'امن و ایمان دینے والا' },
  { number: 7, arabic: 'الْمُهَيْمِن', transliteration: 'Al-Muhaymin', english: 'The Guardian', urdu: 'نگہبان' },
  { number: 8, arabic: 'الْعَزِيز', transliteration: 'Al-Azeez', english: 'The Almighty', urdu: 'غالب' },
  { number: 9, arabic: 'الْجَبَّار', transliteration: 'Al-Jabbar', english: 'The Compeller', urdu: 'زبردست' },
  { number: 10, arabic: 'الْمُتَكَبِّر', transliteration: 'Al-Mutakabbir', english: 'The Supreme in Greatness', urdu: 'بڑائی والا' },
  { number: 11, arabic: 'الْخَالِق', transliteration: 'Al-Khaliq', english: 'The Creator', urdu: 'پیدا کرنے والا' },
  { number: 12, arabic: 'الْبَارِئ', transliteration: "Al-Bari'", english: 'The Originator', urdu: 'بنانے والا' },
  { number: 13, arabic: 'الْمُصَوِّر', transliteration: 'Al-Musawwir', english: 'The Fashioner of Forms', urdu: 'صورت بخشنے والا' },
  { number: 14, arabic: 'الْغَفَّار', transliteration: 'Al-Ghaffar', english: 'The Ever-Forgiving', urdu: 'بہت بخشنے والا' },
  { number: 15, arabic: 'الْقَهَّار', transliteration: 'Al-Qahhar', english: 'The All-Prevailing', urdu: 'سب پر غالب' },
  { number: 16, arabic: 'الْوَهَّاب', transliteration: 'Al-Wahhab', english: 'The Bestower of Gifts', urdu: 'بہت عطا کرنے والا' },
  { number: 17, arabic: 'الرَّزَّاق', transliteration: 'Ar-Razzaq', english: 'The Provider', urdu: 'رزق دینے والا' },
  { number: 18, arabic: 'الْفَتَّاح', transliteration: 'Al-Fattah', english: 'The Opener of Ways', urdu: 'کھولنے والا' },
  { number: 19, arabic: 'الْعَلِيم', transliteration: 'Al-Aleem', english: 'The All-Knowing', urdu: 'سب جاننے والا' },
  { number: 20, arabic: 'الْقَابِض', transliteration: 'Al-Qabid', english: 'The Withholder', urdu: 'تنگی کرنے والا' },
  { number: 21, arabic: 'الْبَاسِط', transliteration: 'Al-Basit', english: 'The Extender', urdu: 'فراخی دینے والا' },
  { number: 22, arabic: 'الْخَافِض', transliteration: 'Al-Khafid', english: 'The Abaser', urdu: 'پست کرنے والا' },
  { number: 23, arabic: 'الرَّافِع', transliteration: "Ar-Rafi'", english: 'The Exalter', urdu: 'بلند کرنے والا' },
  { number: 24, arabic: 'الْمُعِز', transliteration: "Al-Mu'izz", english: 'The Giver of Honour', urdu: 'عزت دینے والا' },
  { number: 25, arabic: 'الْمُذِل', transliteration: 'Al-Muzil', english: 'The Giver of Dishonour', urdu: 'ذلت دینے والا' },
  { number: 26, arabic: 'السَّمِيع', transliteration: "As-Samee'", english: 'The All-Hearing', urdu: 'سب سننے والا' },
  { number: 27, arabic: 'الْبَصِير', transliteration: 'Al-Baseer', english: 'The All-Seeing', urdu: 'سب دیکھنے والا' },
  { number: 28, arabic: 'الْحَكَم', transliteration: 'Al-Hakam', english: 'The Judge', urdu: 'فیصلہ کرنے والا' },
  { number: 29, arabic: 'الْعَدْل', transliteration: "Al-'Adl", english: 'The Utterly Just', urdu: 'انصاف کرنے والا' },
  { number: 30, arabic: 'اللَّطِيف', transliteration: 'Al-Lateef', english: 'The Subtle and Kind', urdu: 'باریک بین، مہربان' },
  { number: 31, arabic: 'الْخَبِير', transliteration: 'Al-Khabeer', english: 'The All-Aware', urdu: 'خبر رکھنے والا' },
  { number: 32, arabic: 'الْحَلِيم', transliteration: 'Al-Haleem', english: 'The Most Forbearing', urdu: 'تحمل والا' },
  { number: 33, arabic: 'الْعَظِيم', transliteration: "Al-'Azeem", english: 'The Magnificent', urdu: 'بہت بڑا' },
  { number: 34, arabic: 'الْغَفُور', transliteration: 'Al-Ghafoor', english: 'The Forgiving', urdu: 'بخشنے والا' },
  { number: 35, arabic: 'الشَّكُور', transliteration: 'Ash-Shakoor', english: 'The Most Appreciative', urdu: 'قدر کرنے والا' },
  { number: 36, arabic: 'الْعَلِي', transliteration: "Al-'Aliyy", english: 'The Most High', urdu: 'سب سے بلند' },
  { number: 37, arabic: 'الْكَبِير', transliteration: 'Al-Kabeer', english: 'The Most Great', urdu: 'سب سے بڑا' },
  { number: 38, arabic: 'الْحَفِيظ', transliteration: 'Al-Hafeez', english: 'The Preserver', urdu: 'حفاظت کرنے والا' },
  { number: 39, arabic: 'الْمُقِيت', transliteration: 'Al-Muqeet', english: 'The Sustainer', urdu: 'قوت پہنچانے والا' },
  { number: 40, arabic: 'الْحَسِيب', transliteration: 'Al-Haseeb', english: 'The Reckoner', urdu: 'حساب لینے والا' },
  { number: 41, arabic: 'الْجَلِيل', transliteration: 'Al-Jaleel', english: 'The Majestic', urdu: 'جلال والا' },
  { number: 42, arabic: 'الْكَرِيم', transliteration: 'Al-Kareem', english: 'The Most Generous', urdu: 'نہایت کرم والا' },
  { number: 43, arabic: 'الرَّقِيب', transliteration: 'Ar-Raqeeb', english: 'The Watchful', urdu: 'نگرانی کرنے والا' },
  { number: 44, arabic: 'الْمُجِيب', transliteration: 'Al-Mujeeb', english: 'The Responder to Prayer', urdu: 'دعا قبول کرنے والا' },
  { number: 45, arabic: 'الْوَاسِع', transliteration: "Al-Wasi'", english: 'The All-Encompassing', urdu: 'وسعت والا' },
  { number: 46, arabic: 'الْحَكِيم', transliteration: 'Al-Hakeem', english: 'The All-Wise', urdu: 'حکمت والا' },
  { number: 47, arabic: 'الْوَدُود', transliteration: 'Al-Wadood', english: 'The Most Loving', urdu: 'بہت محبت کرنے والا' },
  { number: 48, arabic: 'الْمَجِيد', transliteration: 'Al-Majeed', english: 'The Glorious', urdu: 'بزرگی والا' },
  { number: 49, arabic: 'الْبَاعِث', transliteration: "Al-Ba'ith", english: 'The Resurrector', urdu: 'دوبارہ اٹھانے والا' },
  { number: 50, arabic: 'الشَّهِيد', transliteration: 'Ash-Shaheed', english: 'The Witness', urdu: 'گواہ' },
  { number: 51, arabic: 'الْحَق', transliteration: 'Al-Haqq', english: 'The Absolute Truth', urdu: 'سچا' },
  { number: 52, arabic: 'الْوَكِيل', transliteration: 'Al-Wakeel', english: 'The Trustee', urdu: 'کارساز' },
  { number: 53, arabic: 'الْقَوِي', transliteration: 'Al-Qawiyy', english: 'The All-Strong', urdu: 'قوت والا' },
  { number: 54, arabic: 'الْمَتِين', transliteration: 'Al-Mateen', english: 'The Firm', urdu: 'مضبوط' },
  { number: 55, arabic: 'الْوَلِي', transliteration: 'Al-Waliyy', english: 'The Protecting Friend', urdu: 'دوست و مددگار' },
  { number: 56, arabic: 'الْحَمِيد', transliteration: 'Al-Hameed', english: 'The Praiseworthy', urdu: 'تعریف کے لائق' },
  { number: 57, arabic: 'الْمُحْصِي', transliteration: 'Al-Muhsee', english: 'The Accounter', urdu: 'شمار کرنے والا' },
  { number: 58, arabic: 'الْمُبْدِئ', transliteration: "Al-Mubdi'", english: 'The Initiator', urdu: 'ابتدا کرنے والا' },
  { number: 59, arabic: 'الْمُعِيد', transliteration: "Al-Mu'eed", english: 'The Restorer', urdu: 'دوبارہ پیدا کرنے والا' },
  { number: 60, arabic: 'الْمُحْيِي', transliteration: 'Al-Muhyee', english: 'The Giver of Life', urdu: 'زندگی دینے والا' },
  { number: 61, arabic: 'الْمُمِيت', transliteration: 'Al-Mumeet', english: 'The Bringer of Death', urdu: 'موت دینے والا' },
  { number: 62, arabic: 'الْحَي', transliteration: 'Al-Hayy', english: 'The Ever-Living', urdu: 'ہمیشہ زندہ' },
  { number: 63, arabic: 'الْقَيُّوم', transliteration: 'Al-Qayyoom', english: 'The Sustainer of All', urdu: 'سب کو قائم رکھنے والا' },
  { number: 64, arabic: 'الْوَاجِد', transliteration: 'Al-Wajid', english: 'The Perceiver', urdu: 'پا لینے والا' },
  { number: 65, arabic: 'الْمَاجِد', transliteration: 'Al-Majid', english: 'The Illustrious', urdu: 'بزرگ' },
  { number: 66, arabic: 'الْوَاحِد', transliteration: 'Al-Wahid', english: 'The One', urdu: 'اکیلا' },
  { number: 67, arabic: 'الْأَحَد', transliteration: 'Al-Ahad', english: 'The Unique', urdu: 'یکتا' },
  { number: 68, arabic: 'الصَّمَد', transliteration: 'As-Samad', english: 'The Self-Sufficient', urdu: 'بے نیاز' },
  { number: 69, arabic: 'الْقَادِر', transliteration: 'Al-Qadir', english: 'The All-Capable', urdu: 'قدرت والا' },
  { number: 70, arabic: 'الْمُقْتَدِر', transliteration: 'Al-Muqtadir', english: 'The Determiner', urdu: 'پوری قدرت والا' },
  { number: 71, arabic: 'الْمُقَدِّم', transliteration: 'Al-Muqaddim', english: 'The Expediter', urdu: 'آگے کرنے والا' },
  { number: 72, arabic: 'الْمُؤَخِّر', transliteration: "Al-Mu'akhkhir", english: 'The Delayer', urdu: 'پیچھے کرنے والا' },
  { number: 73, arabic: 'الْأَوَّل', transliteration: 'Al-Awwal', english: 'The First', urdu: 'سب سے پہلا' },
  { number: 74, arabic: 'الْآخِر', transliteration: 'Al-Akhir', english: 'The Last', urdu: 'سب سے آخر' },
  { number: 75, arabic: 'الظَّاهِر', transliteration: 'Az-Zahir', english: 'The Manifest', urdu: 'ظاہر' },
  { number: 76, arabic: 'الْبَاطِن', transliteration: 'Al-Batin', english: 'The Hidden', urdu: 'پوشیدہ' },
  { number: 77, arabic: 'الْوَالِي', transliteration: 'Al-Walee', english: 'The Governor', urdu: 'کارفرما' },
  { number: 78, arabic: 'الْمُتَعَالِي', transliteration: "Al-Muta'ali", english: 'The Most Exalted', urdu: 'بہت بلند' },
  { number: 79, arabic: 'الْبَر', transliteration: 'Al-Barr', english: 'The Source of All Goodness', urdu: 'احسان کرنے والا' },
  { number: 80, arabic: 'التَّوَّاب', transliteration: 'At-Tawwab', english: 'The Acceptor of Repentance', urdu: 'توبہ قبول کرنے والا' },
  { number: 81, arabic: 'الْمُنْتَقِم', transliteration: 'Al-Muntaqim', english: 'The Avenger', urdu: 'بدلہ لینے والا' },
  { number: 82, arabic: 'الْعَفُو', transliteration: "Al-'Afuww", english: 'The Pardoner', urdu: 'معاف کرنے والا' },
  { number: 83, arabic: 'الرَّءُوف', transliteration: "Ar-Ra'oof", english: 'The Most Kind', urdu: 'نہایت شفیق' },
  { number: 84, arabic: 'مَالِكُ الْمُلْك', transliteration: 'Malik-ul-Mulk', english: 'Master of the Kingdom', urdu: 'ملک کا مالک' },
  { number: 85, arabic: 'ذُو الْجَلَالِ وَالْإِكْرَام', transliteration: 'Dhul-Jalali wal-Ikram', english: 'Lord of Majesty and Honour', urdu: 'جلال و اکرام والا' },
  { number: 86, arabic: 'الْمُقْسِط', transliteration: 'Al-Muqsit', english: 'The Equitable', urdu: 'انصاف قائم کرنے والا' },
  { number: 87, arabic: 'الْجَامِع', transliteration: "Al-Jami'", english: 'The Gatherer', urdu: 'جمع کرنے والا' },
  { number: 88, arabic: 'الْغَنِي', transliteration: 'Al-Ghaniyy', english: 'The Self-Sufficient', urdu: 'بے نیاز، غنی' },
  { number: 89, arabic: 'الْمُغْنِي', transliteration: 'Al-Mughnee', english: 'The Enricher', urdu: 'غنی کرنے والا' },
  { number: 90, arabic: 'الْمَانِع', transliteration: "Al-Mani'", english: 'The Withholder', urdu: 'روکنے والا' },
  { number: 91, arabic: 'الضَّار', transliteration: 'Ad-Darr', english: 'The Creator of Harm', urdu: 'نقصان دینے والا' },
  { number: 92, arabic: 'النَّافِع', transliteration: "An-Nafi'", english: 'The Bringer of Benefit', urdu: 'نفع دینے والا' },
  { number: 93, arabic: 'النُّور', transliteration: 'An-Noor', english: 'The Light', urdu: 'روشنی' },
  { number: 94, arabic: 'الْهَادِي', transliteration: 'Al-Hadi', english: 'The Guide', urdu: 'ہدایت دینے والا' },
  { number: 95, arabic: 'الْبَدِيع', transliteration: "Al-Badee'", english: 'The Incomparable Originator', urdu: 'بے مثال بنانے والا' },
  { number: 96, arabic: 'الْبَاقِي', transliteration: 'Al-Baqi', english: 'The Everlasting', urdu: 'ہمیشہ باقی رہنے والا' },
  { number: 97, arabic: 'الْوَارِث', transliteration: 'Al-Warith', english: 'The Inheritor of All', urdu: 'سب کا وارث' },
  { number: 98, arabic: 'الرَّشِيد', transliteration: 'Ar-Rasheed', english: 'The Guide to the Right Path', urdu: 'درست راہ دکھانے والا' },
  { number: 99, arabic: 'الصَّبُور', transliteration: 'As-Saboor', english: 'The Most Patient', urdu: 'بہت صبر والا' },
];
