export type DuaEntry = {
  id: string;
  title: string;
  category: DuaCategory;
  arabic: string;
  transliteration: string;
  english: string;
  urdu: string;
  source: string;
};

export const duaCategories = [
  "Morning Duas",
  "Evening Duas",
  "Travel Duas",
  "Sleeping Duas",
  "Eating Duas",
  "Masjid Duas",
  "Protection Duas",
  "Ramadan Duas",
] as const;

export type DuaCategory = (typeof duaCategories)[number];

export const duaCollection: DuaEntry[] = [
  {
    id: "morning-1",
    title: "Upon Waking Up",
    category: "Morning Duas",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
    transliteration: "Alhamdu lillahil-lathee ahyana ba'da ma amatana wa ilayhin-nushoor",
    english: "All praise is for Allah who gave us life after death, and to Him is the return.",
    urdu: "تمام تعریف اللہ کے لیے ہے جس نے ہمیں موت کے بعد زندگی دی اور اُسی کی طرف لوٹنا ہے۔",
    source: "Sahih al-Bukhari 6312",
  },
  {
    id: "morning-2",
    title: "Morning Remembrance",
    category: "Morning Duas",
    arabic: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ رَبِّ الْعَالَمِينَ",
    transliteration: "Asbahna wa asbahal-mulku lillahi rabbil-'alameen",
    english: "We have entered the morning and with it all dominion belongs to Allah, Lord of the worlds.",
    urdu: "ہم نے صبح کی اور ساری بادشاہی اللہ رب العالمین کی ہے۔",
    source: "Sunan Abi Dawud 5071",
  },
  {
    id: "morning-3",
    title: "Seeking a Good Day",
    category: "Morning Duas",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ هَذَا الْيَوْمِ فَتْحَهُ وَنَصْرَهُ وَنُورَهُ وَبَرَكَتَهُ",
    transliteration: "Allahumma innee as'aluka khayra hathal-yawmi fathahu wa nasrahu wa noorahu wa barakatahu",
    english: "O Allah, I ask You for the good of this day: its opening, its help, its light and its blessing.",
    urdu: "اے اللہ! میں تجھ سے اس دن کی بھلائی، فتح، نصرت، نور اور برکت مانگتا ہوں۔",
    source: "Sunan Abi Dawud 5084",
  },
  {
    id: "evening-1",
    title: "Evening Remembrance",
    category: "Evening Duas",
    arabic: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ رَبِّ الْعَالَمِينَ",
    transliteration: "Amsayna wa amsal-mulku lillahi rabbil-'alameen",
    english: "We have entered the evening and with it all dominion belongs to Allah, Lord of the worlds.",
    urdu: "ہم نے شام کی اور ساری بادشاہی اللہ رب العالمین کی ہے۔",
    source: "Sunan Abi Dawud 5071",
  },
  {
    id: "evening-2",
    title: "Protection at Nightfall",
    category: "Evening Duas",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    transliteration: "A'oothu bikalimatil-lahit-tammati min sharri ma khalaq",
    english: "I seek refuge in the perfect words of Allah from the evil of what He created.",
    urdu: "میں اللہ کے کامل کلمات کی پناہ لیتا ہوں ہر اُس چیز کے شر سے جو اُس نے پیدا کی۔",
    source: "Sahih Muslim 2709",
  },
  {
    id: "evening-3",
    title: "Gratitude for the Day",
    category: "Evening Duas",
    arabic: "اللَّهُمَّ بِكَ أَمْسَيْنَا وَبِكَ أَصْبَحْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ",
    transliteration: "Allahumma bika amsayna wa bika asbahna wa bika nahya wa bika namoot",
    english: "O Allah, by You we enter the evening and the morning, by You we live and by You we die.",
    urdu: "اے اللہ! تیرے ہی سہارے شام اور صبح کرتے ہیں، تیرے ہی سہارے جیتے اور مرتے ہیں۔",
    source: "Jami at-Tirmidhi 3391",
  },
  {
    id: "travel-1",
    title: "Dua When Boarding",
    category: "Travel Duas",
    arabic: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ",
    transliteration: "Subhanal-lathee sakhkhara lana hatha wa ma kunna lahu muqrineen",
    english: "Glory to Him who has subjected this to us, and we could never have it by our own power.",
    urdu: "پاک ہے وہ جس نے اسے ہمارے تابع کیا، ورنہ ہم اسے قابو میں نہ لا سکتے تھے۔",
    source: "Surah Az-Zukhruf 43:13",
  },
  {
    id: "travel-2",
    title: "Dua for a Safe Journey",
    category: "Travel Duas",
    arabic: "اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى",
    transliteration: "Allahumma inna nas'aluka fee safarina hathal-birra wat-taqwa",
    english: "O Allah, we ask You for righteousness and piety in this journey of ours.",
    urdu: "اے اللہ! ہم اپنے اس سفر میں تجھ سے نیکی اور تقویٰ کا سوال کرتے ہیں۔",
    source: "Sahih Muslim 1342",
  },
  {
    id: "travel-3",
    title: "Arriving at a New Place",
    category: "Travel Duas",
    arabic: "اللَّهُمَّ رَبَّ السَّمَاوَاتِ السَّبْعِ وَمَا أَظْلَلْنَ أَسْأَلُكَ خَيْرَهَا",
    transliteration: "Allahumma rabbas-samawatis-sab'i wa ma azlalna as'aluka khayraha",
    english: "O Allah, Lord of the seven heavens and all they shade, I ask You for the good of this place.",
    urdu: "اے اللہ! ساتوں آسمانوں کے رب، میں تجھ سے اس جگہ کی بھلائی مانگتا ہوں۔",
    source: "Sunan an-Nasa'i 8812",
  },
  {
    id: "sleep-1",
    title: "Before Sleeping",
    category: "Sleeping Duas",
    arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
    transliteration: "Bismika Allahumma amootu wa ahya",
    english: "In Your name, O Allah, I die and I live.",
    urdu: "اے اللہ! تیرے نام سے میں مرتا اور جیتا ہوں۔",
    source: "Sahih al-Bukhari 6324",
  },
  {
    id: "sleep-2",
    title: "Entrusting the Soul",
    category: "Sleeping Duas",
    arabic: "اللَّهُمَّ أَسْلَمْتُ نَفْسِي إِلَيْكَ وَوَجَّهْتُ وَجْهِي إِلَيْكَ",
    transliteration: "Allahumma aslamtu nafsee ilayka wa wajjahtu wajhee ilayk",
    english: "O Allah, I submit myself to You and turn my face toward You.",
    urdu: "اے اللہ! میں نے اپنی جان تیرے سپرد کی اور اپنا رخ تیری طرف کیا۔",
    source: "Sahih al-Bukhari 247",
  },
  {
    id: "sleep-3",
    title: "Protection While Asleep",
    category: "Sleeping Duas",
    arabic: "اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ",
    transliteration: "Allahumma qinee 'athabaka yawma tab'athu 'ibadak",
    english: "O Allah, protect me from Your punishment on the Day You resurrect Your servants.",
    urdu: "اے اللہ! مجھے اُس دن کے عذاب سے بچا جب تو اپنے بندوں کو اٹھائے گا۔",
    source: "Sunan Abi Dawud 5045",
  },
  {
    id: "eating-1",
    title: "Before Eating",
    category: "Eating Duas",
    arabic: "بِسْمِ اللَّهِ وَعَلَى بَرَكَةِ اللَّهِ",
    transliteration: "Bismillahi wa 'ala barakatillah",
    english: "In the name of Allah and with the blessing of Allah.",
    urdu: "اللہ کے نام سے اور اللہ کی برکت کے ساتھ۔",
    source: "Sunan Abi Dawud 3767",
  },
  {
    id: "eating-2",
    title: "After Eating",
    category: "Eating Duas",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ",
    transliteration: "Alhamdu lillahil-lathee at'amana wa saqana wa ja'alana muslimeen",
    english: "All praise is for Allah who fed us, gave us drink, and made us Muslims.",
    urdu: "تمام تعریف اللہ کی جس نے ہمیں کھلایا، پلایا اور مسلمان بنایا۔",
    source: "Jami at-Tirmidhi 3457",
  },
  {
    id: "eating-3",
    title: "Blessing in Provision",
    category: "Eating Duas",
    arabic: "اللَّهُمَّ بَارِكْ لَنَا فِيهِ وَأَطْعِمْنَا خَيْرًا مِنْهُ",
    transliteration: "Allahumma barik lana feehi wa at'imna khayran minhu",
    english: "O Allah, bless this for us and feed us better than it.",
    urdu: "اے اللہ! ہمارے لیے اس میں برکت دے اور اس سے بہتر عطا فرما۔",
    source: "Jami at-Tirmidhi 3455",
  },
  {
    id: "masjid-1",
    title: "Entering the Masjid",
    category: "Masjid Duas",
    arabic: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
    transliteration: "Allahummaf-tah lee abwaba rahmatik",
    english: "O Allah, open for me the doors of Your mercy.",
    urdu: "اے اللہ! میرے لیے اپنی رحمت کے دروازے کھول دے۔",
    source: "Sahih Muslim 713",
  },
  {
    id: "masjid-2",
    title: "Leaving the Masjid",
    category: "Masjid Duas",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ",
    transliteration: "Allahumma innee as'aluka min fadlik",
    english: "O Allah, I ask You from Your bounty.",
    urdu: "اے اللہ! میں تجھ سے تیرے فضل کا سوال کرتا ہوں۔",
    source: "Sahih Muslim 713",
  },
  {
    id: "masjid-3",
    title: "Hearing the Adhan",
    category: "Masjid Duas",
    arabic: "اللَّهُمَّ رَبَّ هَذِهِ الدَّعْوَةِ التَّامَّةِ آتِ مُحَمَّدًا الْوَسِيلَةَ وَالْفَضِيلَةَ",
    transliteration: "Allahumma rabba hathihid-da'watit-tammati ati Muhammadanil-waseelata wal-fadeelah",
    english: "O Allah, Lord of this perfect call, grant Muhammad ﷺ the station of nearness and excellence.",
    urdu: "اے اللہ! اس کامل پکار کے رب، محمد ﷺ کو وسیلہ اور فضیلت عطا فرما۔",
    source: "Sahih al-Bukhari 614",
  },
  {
    id: "protect-1",
    title: "Complete Protection",
    category: "Protection Duas",
    arabic: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ",
    transliteration: "Bismillahil-lathee la yadurru ma'a ismihi shay'un fil-ardi wa la fis-sama'",
    english: "In the name of Allah, with whose name nothing in the earth or the heaven can cause harm.",
    urdu: "اللہ کے نام سے، جس کے نام کے ساتھ زمین و آسمان میں کوئی چیز نقصان نہیں دے سکتی۔",
    source: "Sunan Abi Dawud 5088",
  },
  {
    id: "protect-2",
    title: "Refuge from Anxiety",
    category: "Protection Duas",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ",
    transliteration: "Allahumma innee a'oothu bika minal-hammi wal-hazan",
    english: "O Allah, I seek refuge in You from anxiety and sorrow.",
    urdu: "اے اللہ! میں غم اور پریشانی سے تیری پناہ چاہتا ہوں۔",
    source: "Sahih al-Bukhari 6369",
  },
  {
    id: "protect-3",
    title: "Trust in Allah",
    category: "Protection Duas",
    arabic: "حَسْبِيَ اللَّهُ وَنِعْمَ الْوَكِيلُ",
    transliteration: "Hasbiyal-lahu wa ni'mal-wakeel",
    english: "Allah is sufficient for me, and He is the best disposer of affairs.",
    urdu: "میرے لیے اللہ کافی ہے اور وہ بہترین کارساز ہے۔",
    source: "Surah Aal-Imran 3:173",
  },
  {
    id: "ramadan-1",
    title: "Intention for Fasting",
    category: "Ramadan Duas",
    arabic: "وَبِصَوْمِ غَدٍ نَّوَيْتُ مِنْ شَهْرِ رَمَضَانَ",
    transliteration: "Wa bisawmi ghadin nawaytu min shahri Ramadan",
    english: "I intend to fast tomorrow in the month of Ramadan.",
    urdu: "میں نے رمضان کے مہینے میں کل کے روزے کی نیت کی۔",
    source: "Sunan Abi Dawud 2454",
  },
  {
    id: "ramadan-2",
    title: "Breaking the Fast",
    category: "Ramadan Duas",
    arabic: "ذَهَبَ الظَّمَأُ وَابْتَلَّتِ الْعُرُوقُ وَثَبَتَ الْأَجْرُ إِنْ شَاءَ اللَّهُ",
    transliteration: "Thahabaz-zama'u wabtallatil-'urooqu wa thabatal-ajru in sha' Allah",
    english: "Thirst is gone, the veins are moistened, and the reward is certain, if Allah wills.",
    urdu: "پیاس مٹ گئی، رگیں تر ہو گئیں اور انشاءاللہ اجر ثابت ہو گیا۔",
    source: "Sunan Abi Dawud 2357",
  },
  {
    id: "ramadan-3",
    title: "Dua of Laylatul Qadr",
    category: "Ramadan Duas",
    arabic: "اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي",
    transliteration: "Allahumma innaka 'afuwwun tuhibbul-'afwa fa'fu 'annee",
    english: "O Allah, You are Most Forgiving and love forgiveness, so forgive me.",
    urdu: "اے اللہ! تو معاف کرنے والا ہے اور معافی پسند کرتا ہے، پس مجھے معاف کر دے۔",
    source: "Jami at-Tirmidhi 3513",
  },
];
