/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DuasRouteImport } from './routes/duas'
import { Route as HadithRouteImport } from './routes/hadith'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as KidsRouteImport } from './routes/kids'
import { Route as NamesRouteImport } from './routes/names'
import { Route as PrayerTimesRouteImport } from './routes/prayer-times'
import { Route as QiblaRouteImport } from './routes/qibla'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as QuranRouteImport } from './routes/quran'
import { Route as ZakatRouteImport } from './routes/zakat'
import { Route as QuranIndexRouteImport } from './routes/quran.index'
import { Route as QuranSurahIdRouteImport } from './routes/quran.$surahId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DuasRoute = DuasRouteImport.update({
  id: '/duas',
  path: '/duas',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithRoute = HadithRouteImport.update({
  id: '/hadith',
  path: '/hadith',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsRoute = KidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => rootRouteImport,
} as any)
const NamesRoute = NamesRouteImport.update({
  id: '/names',
  path: '/names',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerTimesRoute = PrayerTimesRouteImport.update({
  id: '/prayer-times',
  path: '/prayer-times',
  getParentRoute: () => rootRouteImport,
} as any)
const QiblaRoute = QiblaRouteImport.update({
  id: '/qibla',
  path: '/qibla',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranRoute = QuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => rootRouteImport,
} as any)
const ZakatRoute = ZakatRouteImport.update({
  id: '/zakat',
  path: '/zakat',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranIndexRoute = QuranIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuranRoute,
} as any)
const QuranSurahIdRoute = QuranSurahIdRouteImport.update({
  id: '/$surahId',
  path: '/$surahId',
  getParentRoute: () => QuranRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/articles': typeof ArticlesRoute
  '/contact': typeof ContactRoute
  '/duas': typeof DuasRoute
  '/hadith': typeof HadithRoute
  '/history': typeof HistoryRoute
  '/kids': typeof KidsRoute
  '/names': typeof NamesRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/qibla': typeof QiblaRoute
  '/quiz': typeof QuizRoute
  '/quran': typeof QuranRouteWithChildren
  '/zakat': typeof ZakatRoute
  '/quran/$surahId': typeof QuranSurahIdRoute
  '/quran/': typeof QuranIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/articles': typeof ArticlesRoute
  '/contact': typeof ContactRoute
  '/duas': typeof DuasRoute
  '/hadith': typeof HadithRoute
  '/history': typeof HistoryRoute
  '/kids': typeof KidsRoute
  '/names': typeof NamesRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/qibla': typeof QiblaRoute
  '/quiz': typeof QuizRoute
  '/zakat': typeof ZakatRoute
  '/quran/$surahId': typeof QuranSurahIdRoute
  '/quran': typeof QuranIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/articles': typeof ArticlesRoute
  '/contact': typeof ContactRoute
  '/duas': typeof DuasRoute
  '/hadith': typeof HadithRoute
  '/history': typeof HistoryRoute
  '/kids': typeof KidsRoute
  '/names': typeof NamesRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/qibla': typeof QiblaRoute
  '/quiz': typeof QuizRoute
  '/quran': typeof QuranRouteWithChildren
  '/zakat': typeof ZakatRoute
  '/quran/$surahId': typeof QuranSurahIdRoute
  '/quran/': typeof QuranIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/articles'
    | '/contact'
    | '/duas'
    | '/hadith'
    | '/history'
    | '/kids'
    | '/names'
    | '/prayer-times'
    | '/qibla'
    | '/quiz'
    | '/quran'
    | '/zakat'
    | '/quran/$surahId'
    | '/quran/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/articles'
    | '/contact'
    | '/duas'
    | '/hadith'
    | '/history'
    | '/kids'
    | '/names'
    | '/prayer-times'
    | '/qibla'
    | '/quiz'
    | '/zakat'
    | '/quran/$surahId'
    | '/quran'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/articles'
    | '/contact'
    | '/duas'
    | '/hadith'
    | '/history'
    | '/kids'
    | '/names'
    | '/prayer-times'
    | '/qibla'
    | '/quiz'
    | '/quran'
    | '/zakat'
    | '/quran/$surahId'
    | '/quran/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRoute
  ArticlesRoute: typeof ArticlesRoute
  ContactRoute: typeof ContactRoute
  DuasRoute: typeof DuasRoute
  HadithRoute: typeof HadithRoute
  HistoryRoute: typeof HistoryRoute
  KidsRoute: typeof KidsRoute
  NamesRoute: typeof NamesRoute
  PrayerTimesRoute: typeof PrayerTimesRoute
  QiblaRoute: typeof QiblaRoute
  QuizRoute: typeof QuizRoute
  QuranRoute: typeof QuranRouteWithChildren
  ZakatRoute: typeof ZakatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duas': {
      id: '/duas'
      path: '/duas'
      fullPath: '/duas'
      preLoaderRoute: typeof DuasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith': {
      id: '/hadith'
      path: '/hadith'
      fullPath: '/hadith'
      preLoaderRoute: typeof HadithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids': {
      id: '/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof KidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/names': {
      id: '/names'
      path: '/names'
      fullPath: '/names'
      preLoaderRoute: typeof NamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-times': {
      id: '/prayer-times'
      path: '/prayer-times'
      fullPath: '/prayer-times'
      preLoaderRoute: typeof PrayerTimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qibla': {
      id: '/qibla'
      path: '/qibla'
      fullPath: '/qibla'
      preLoaderRoute: typeof QiblaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran': {
      id: '/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof QuranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zakat': {
      id: '/zakat'
      path: '/zakat'
      fullPath: '/zakat'
      preLoaderRoute: typeof ZakatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/': {
      id: '/quran/'
      path: '/'
      fullPath: '/quran/'
      preLoaderRoute: typeof QuranIndexRouteImport
      parentRoute: typeof QuranRoute
    }
    '/quran/$surahId': {
      id: '/quran/$surahId'
      path: '/$surahId'
      fullPath: '/quran/$surahId'
      preLoaderRoute: typeof QuranSurahIdRouteImport
      parentRoute: typeof QuranRoute
    }
  }
}

interface QuranRouteChildren {
  QuranSurahIdRoute: typeof QuranSurahIdRoute
  QuranIndexRoute: typeof QuranIndexRoute
}

const QuranRouteChildren: QuranRouteChildren = {
  QuranSurahIdRoute: QuranSurahIdRoute,
  QuranIndexRoute: QuranIndexRoute,
}

const QuranRouteWithChildren = QuranRoute._addFileChildren(QuranRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRoute,
  ArticlesRoute: ArticlesRoute,
  ContactRoute: ContactRoute,
  DuasRoute: DuasRoute,
  HadithRoute: HadithRoute,
  HistoryRoute: HistoryRoute,
  KidsRoute: KidsRoute,
  NamesRoute: NamesRoute,
  PrayerTimesRoute: PrayerTimesRoute,
  QiblaRoute: QiblaRoute,
  QuizRoute: QuizRoute,
  QuranRoute: QuranRouteWithChildren,
  ZakatRoute: ZakatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
